name: Test
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0]
        gemfile: [activerecord-5.2.Gemfile, activerecord-6.0.Gemfile, activerecord-6.1.Gemfile, activerecord-7.0.Gemfile]
        exclude:
          - ruby: 3.0
            gemfile: activerecord-5.2.Gemfile
    env:
      BUNDLE_GEMFILE: gemfiles/${{matrix.gemfile}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # Also installs gems
      - name: Run tests
        run: bundle exec rake test
