name: Test
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, 3.4]
        gemfile: [activerecord-7.1.Gemfile, activerecord-7.2.Gemfile]
    env:
      BUNDLE_GEMFILE: gemfiles/${{matrix.gemfile}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # Also installs gems
      - name: Run tests
        run: bundle exec rake test
